#### NumPy (Numerical Python)
It is a python library designed for working with numbers, arrays, matrices, and mathematical operations efficiently.

#### Vector
A vector is a one-dimensional collection of numerical values.

In [4]:
import numpy as np

print(np.__version__)


numbers=np.array([1,2,3,4,5,6,7,7,8])
print(numbers)
print(type(numbers))

2.5.2
[1 2 3 4 5 6 7 7 8]
<class 'numpy.ndarray'>


#### Matrix
A matrix is a two-dimensional arrangement of numbers organized into rows and columns.

In [5]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
## Get Dimensions
print(numbers.ndim)
matrix.ndim

1


2

In [9]:
## Get shape
print(numbers.shape)
matrix.shape

(9,)


(2, 3)

In [10]:
## Get type
numbers.dtype

dtype('int64')

In [13]:
## get size 
print(numbers.size)
print(matrix.size)

9
6


In [17]:
## zeros

arr=np.zeros(5)
print(arr)
arr1=np.zeros((2,3))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
## ones

arr=np.ones(5)
print(arr)
arr1=np.ones((3,4))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
## arrange
arr=np.arange(5)
print(arr)
arr1=np.arange(1,10,2)
print(arr1)

[0 1 2 3 4]
[1 3 5 7 9]
